### ISSUE TITLE
ModuleNotFoundError: No module named 'prompt_toolkit.key_binding.manager'

### ISSUE THREAD

**Issue by qazxwecvr** [ergonomica/ergonomica#108]
I'm running Arch GNU/Linux. I've installed the latest python version (3.8.5) and ran `pip install ergonomica`. I `cd`'d into `~/.local/bin` and ran `./ergonoica`, and got the following message:
Traceback (most recent call last):
  File "/home/qazxwecvr/.local/bin/ergonomica", line 33, in <module>
    sys.exit(load_entry_point('ergonomica==2.5.7', 'console_scripts', 'ergonomica')())
  File "/home/qazxwecvr/.local/bin/ergonomica", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/qazxwecvr/.local/lib/python3.8/site-packages/ergonomica/main.py", line 21, in <module>
    from ergonomica.lib.interface.prompt import prompt
  File "/home/qazxwecvr/.local/lib/python3.8/site-packages/ergonomica/lib/interface/prompt.py", line 20, in <module>
    from ergonomica.lib.interface.key_bindings_manager import manager_for_environment
  File "/home/qazxwecvr/.local/lib/python3.8/site-packages/ergonomica/lib/interface/key_bindings_manager.py", line 18, in <module>
    from prompt_toolkit.key_binding.manager import KeyBindingManager
ModuleNotFoundError: No module named 'prompt_toolkit.key_binding.manager'
I made sure to run `pip install prompt_toolkit`, to no avail. It seems like this attribute of `prompt_toolkit.key_binding` is [depricated](https://github.com/prompt-toolkit/python-prompt-toolkit/issues/455).

#Steps to Reproduce
1. Run `pip install ergonomica`
2. Run `pip install prompt_toolkit`
3. `cd` into the directory with the executable
4. Run `./ergonomica`

**Comment by hexdump** [comment]
Resolved in PR #106!

I haven't gotten a change to work on this project for years, but I'm picking it back up again; expect more progress soon.
