### ISSUE TITLE
No module named pyvim.entry_points.run_pyvim

### ISSUE THREAD

**Issue by funkotron** [ergonomica/ergonomica#52]
Installed on OSX as per instructions

Get the error:
```
Traceback (most recent call last):
  File "/usr/local/bin/ergonomica.py", line 55, in <module>
    from lib.lang.error_handler import handle_runtime_error
  File "/usr/local/Cellar/ergonomica/1.1.3/bin/lib/lang/error_handler.py", line 20, in <module>
    from lib.load.load_commands import verbs
  File "/usr/local/Cellar/ergonomica/1.1.3/bin/lib/load/load_commands.py", line 23, in <module>
    from lib.lib import verbs
  File "/usr/local/Cellar/ergonomica/1.1.3/bin/lib/lib/__init__.py", line 22, in <module>
    verbs.update(__import__('lib.lib.'+item, globals(), locals(), ['object'], 0).verbs)
  File "/usr/local/Cellar/ergonomica/1.1.3/bin/lib/lib/edit.py", line 36, in <module>
    from pyvim.entry_points.run_pyvim import run
ImportError: No module named pyvim.entry_points.run_pyvim
```

Tried installing pyvim at version 0.0.20 but still no luck.

**Comment by Schtolc** [comment]
Hi! I've just tried to install ergonomica on macOS Sierra 10.12.2.
```
pip install pyflakes pyvim
ergo_setup.sh
```
- fixed error for me.

We are working on pip packet atm, so there won't be any of this problems. Issue#45

**Comment by lschumm** [comment]
Pip package is now created, and Homebrew instructions (which didn't specify to install pyvim) are fixed on wiki.
