### ISSUE TITLE
ModuleNotFoundError: No module named 'prompt_toolkit.key_binding.bindings.utils'

### ISSUE THREAD

**Issue by vmiroshnik** [ergonomica/ergonomica#60]
There is no "utils" in "prompt_toolkit.key_binding.bindings".
When launching ergonomica in msys/Windows.
![ergonomica_import_error](https://cloud.githubusercontent.com/assets/12794805/23403236/e5cc3c0a-fdb7-11e6-8325-b783f3c02984.PNG)

**Comment by leotada** [comment]
In my Manjaro Linux x64 i have this error too.

**Comment by lalmeras** [comment]
Same on Fedora 26

```
Traceback (most recent call last):
  File "/home/lalmeras/.virtualenvs/ergonomica/bin/ergonomica", line 7, in <module>
    from ergonomica.ergo import ergo
  File "/home/lalmeras/.virtualenvs/ergonomica/lib/python3.6/site-packages/ergonomica/ergo.py", line 54, in <module>
    from ergonomica.lib.lang.error_handler import handle_runtime_error
  File "/home/lalmeras/.virtualenvs/ergonomica/lib/python3.6/site-packages/ergonomica/lib/lang/error_handler.py", line 20, in <module>
    from ergonomica.lib.load.load_commands import verbs
  File "/home/lalmeras/.virtualenvs/ergonomica/lib/python3.6/site-packages/ergonomica/lib/load/load_commands.py", line 23, in <module>
    from ergonomica.lib.lib import verbs
  File "/home/lalmeras/.virtualenvs/ergonomica/lib/python3.6/site-packages/ergonomica/lib/lib/__init__.py", line 63, in <module>
    verbs.update(__import__('ergonomica.lib.lib.'+item, globals(), locals(), ['object'], 0).verbs)
  File "/home/lalmeras/.virtualenvs/ergonomica/lib/python3.6/site-packages/ergonomica/lib/lib/edit.py", line 36, in <module>
    from pyvim.entry_points.run_pyvim import run
  File "/home/lalmeras/.virtualenvs/ergonomica/lib/python3.6/site-packages/pyvim/entry_points/run_pyvim.py", line 17, in <module>
    from pyvim.editor import Editor
  File "/home/lalmeras/.virtualenvs/ergonomica/lib/python3.6/site-packages/pyvim/editor.py", line 28, in <module>
    from .key_bindings import create_key_bindings
  File "/home/lalmeras/.virtualenvs/ergonomica/lib/python3.6/site-packages/pyvim/key_bindings.py", line 4, in <module>
    from prompt_toolkit.key_binding.bindings.utils import create_handle_decorator
ModuleNotFoundError: No module named 'prompt_toolkit.key_binding.bindings.utils'
```

**Comment by lschumm** [comment]
I believe this error resulted from Ergonomica 1.2.4 (an ancient version) which was the default PyPI version (since the newer versions were flagged as betas and release candidates). This should be fixed on the latest PyPI version (2.0.5).

**Comment by lalmeras** [comment]
I don't know which version I installed, but I now reinstalled it, it is now 2.0.5 and I get rid of this error.

**Comment by lschumm** [comment]
Great, closing this issue.
