### ISSUE TITLE
echo printing new lines for every character

### ISSUE THREAD

**Issue by dpp2000** [ergonomica/ergonomica#7]
[ergo: nayhd in /}> echo [test]
STDOUT IS ['t', 'e', 's', 't']
t
e
s
t

**Comment by lschumm** [comment]
even worse: now is
```
[ergo: lschumm in /}> echo [test]
Traceback (most recent call last):
  File "/Users/lschumm/ergonomica/ergonomica.py", line 49, in <module>
    STDOUT = verbs.verbs[BLOCKS[i][0][0]](LAST, {s.split(":")[0]:s.split(":")[1] for s in BLOCKS[i][2]})
  File "/Users/lschumm/ergonomica/verbs/verbs.py", line 72, in echo
    return args[0]
IndexError: list index out of range
```
